### ISSUE TITLE
monitor DPI is not managed through SDL2

### ISSUE THREAD

**Issue by abakobo** [immortalx74/SDLUI#3]
The DPI awareness is managed with the WIN32 API.
For the SLDUI to be cross platform it would be nice to have it managed by SDL2, I think SDL2 is HiDPI able since 2.0.11

Is it the only reason why you include some WIN32 stuff?

**Comment by immortalx74** [comment]
To be honest I've no idea. I think I've read somewhere that it's Windows that's somewhat weird on how it handles HiDPI, thus why I included the WIN32 stuff (also it's the only platform I'm using).
There's actually more to be done like detecting Windows scaling changes. If SDL2 can manage this it would be really nice.
